#pragma once


namespace Happic { namespace Rendering {

	enum TextureFormat
	{
		//4 component texture formats
		TEXTURE_FORMAT_RGBA8_UNORM,
		TEXTURE_FORMAT_RGBA16_UNORM,
		TEXTURE_FORMAT_RGBA16_FLOAT,
		TEXTURE_FORMAT_RGBA32_FLOAT,

		//3 component texture formats
		TEXTURE_FORMAT_RGB8_UNORM,
		TEXTURE_FORMAT_RGB16_UNORM,
		TEXTURE_FORMAT_RGB16_FLOAT,
		TEXTURE_FORMAT_RGB32_FLOAT,

		//2 component texture format
		TEXTURE_FORMAT_RG8_UNORM,
		TEXTURE_FORMAT_RG16_UNORM,
		TEXTURE_FORMAT_RG16_FLOAT,
		TEXTURE_FORMAT_RG32_FLOAT,

		//1 component texture formats
		TEXTURE_FORMAT_R8_UNORM,
		TEXTURE_FORMAT_R16_UNORM,
		TEXTURE_FORMAT_R16_FLOAT,
		TEXTURE_FORMAT_R32_FLOAT,

		//Depth formats
		TEXTURE_FORMAT_DEPTH16_UNORM,
		TEXTURE_FORMAT_DEPTH16_UNORM_STENCIL8_UINT,
		TEXTURE_FORMAT_DEPTH24_UNORM_STENCIL8_UINT,
		TEXTURE_FORMAT_DEPTH32_FLOAT,
		TEXTURE_FORMAT_DEPTH32_FLOAT_STENCIL8_UINT
	};

	class ITexture
	{
	public:
		
	};

} }
